// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricValue.proto

package cn.betasoft.dp.metric.merge.protobuf;

/**
 * Protobuf type {@code MetricValue}
 */
public final class MetricValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MetricValue)
    MetricValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetricValue.newBuilder() to construct.
  private MetricValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetricValue() {
    moType_ = "";
    metricName_ = "";
    moId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetricValue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetricValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            moType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            metricName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            moId_ = s;
            break;
          }
          case 33: {

            metricValue_ = input.readDouble();
            break;
          }
          case 40: {

            sampleTime_ = input.readInt64();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              metricTags_ = com.google.protobuf.MapField.newMapField(
                  MetricTagsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            metricTags__ = input.readMessage(
                MetricTagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            metricTags_.getMutableMap().put(
                metricTags__.getKey(), metricTags__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetMetricTags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.betasoft.dp.metric.merge.protobuf.MetricValue.class, cn.betasoft.dp.metric.merge.protobuf.MetricValue.Builder.class);
  }

  public static final int MOTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object moType_;
  /**
   * <code>string moType = 1;</code>
   * @return The moType.
   */
  @java.lang.Override
  public java.lang.String getMoType() {
    java.lang.Object ref = moType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moType_ = s;
      return s;
    }
  }
  /**
   * <code>string moType = 1;</code>
   * @return The bytes for moType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoTypeBytes() {
    java.lang.Object ref = moType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object metricName_;
  /**
   * <code>string metricName = 2;</code>
   * @return The metricName.
   */
  @java.lang.Override
  public java.lang.String getMetricName() {
    java.lang.Object ref = metricName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metricName_ = s;
      return s;
    }
  }
  /**
   * <code>string metricName = 2;</code>
   * @return The bytes for metricName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetricNameBytes() {
    java.lang.Object ref = metricName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metricName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOID_FIELD_NUMBER = 3;
  private volatile java.lang.Object moId_;
  /**
   * <code>string moId = 3;</code>
   * @return The moId.
   */
  @java.lang.Override
  public java.lang.String getMoId() {
    java.lang.Object ref = moId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moId_ = s;
      return s;
    }
  }
  /**
   * <code>string moId = 3;</code>
   * @return The bytes for moId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoIdBytes() {
    java.lang.Object ref = moId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICVALUE_FIELD_NUMBER = 4;
  private double metricValue_;
  /**
   * <code>double metricValue = 4;</code>
   * @return The metricValue.
   */
  @java.lang.Override
  public double getMetricValue() {
    return metricValue_;
  }

  public static final int SAMPLETIME_FIELD_NUMBER = 5;
  private long sampleTime_;
  /**
   * <code>int64 sampleTime = 5;</code>
   * @return The sampleTime.
   */
  @java.lang.Override
  public long getSampleTime() {
    return sampleTime_;
  }

  public static final int METRICTAGS_FIELD_NUMBER = 6;
  private static final class MetricTagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_MetricTagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metricTags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetricTags() {
    if (metricTags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetricTagsDefaultEntryHolder.defaultEntry);
    }
    return metricTags_;
  }

  public int getMetricTagsCount() {
    return internalGetMetricTags().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */

  @java.lang.Override
  public boolean containsMetricTags(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMetricTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetricTagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetricTags() {
    return getMetricTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMetricTagsMap() {
    return internalGetMetricTags().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getMetricTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetricTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  @java.lang.Override

  public java.lang.String getMetricTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetricTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMoTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, moType_);
    }
    if (!getMetricNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metricName_);
    }
    if (!getMoIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, moId_);
    }
    if (metricValue_ != 0D) {
      output.writeDouble(4, metricValue_);
    }
    if (sampleTime_ != 0L) {
      output.writeInt64(5, sampleTime_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetricTags(),
        MetricTagsDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMoTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, moType_);
    }
    if (!getMetricNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metricName_);
    }
    if (!getMoIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, moId_);
    }
    if (metricValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, metricValue_);
    }
    if (sampleTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, sampleTime_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetricTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metricTags__ = MetricTagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, metricTags__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.betasoft.dp.metric.merge.protobuf.MetricValue)) {
      return super.equals(obj);
    }
    cn.betasoft.dp.metric.merge.protobuf.MetricValue other = (cn.betasoft.dp.metric.merge.protobuf.MetricValue) obj;

    if (!getMoType()
        .equals(other.getMoType())) return false;
    if (!getMetricName()
        .equals(other.getMetricName())) return false;
    if (!getMoId()
        .equals(other.getMoId())) return false;
    if (java.lang.Double.doubleToLongBits(getMetricValue())
        != java.lang.Double.doubleToLongBits(
            other.getMetricValue())) return false;
    if (getSampleTime()
        != other.getSampleTime()) return false;
    if (!internalGetMetricTags().equals(
        other.internalGetMetricTags())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMoType().hashCode();
    hash = (37 * hash) + METRICNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMetricName().hashCode();
    hash = (37 * hash) + MOID_FIELD_NUMBER;
    hash = (53 * hash) + getMoId().hashCode();
    hash = (37 * hash) + METRICVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMetricValue()));
    hash = (37 * hash) + SAMPLETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSampleTime());
    if (!internalGetMetricTags().getMap().isEmpty()) {
      hash = (37 * hash) + METRICTAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetricTags().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.betasoft.dp.metric.merge.protobuf.MetricValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MetricValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MetricValue)
      cn.betasoft.dp.metric.merge.protobuf.MetricValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMetricTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableMetricTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.betasoft.dp.metric.merge.protobuf.MetricValue.class, cn.betasoft.dp.metric.merge.protobuf.MetricValue.Builder.class);
    }

    // Construct using cn.betasoft.dp.metric.merge.protobuf.MetricValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      moType_ = "";

      metricName_ = "";

      moId_ = "";

      metricValue_ = 0D;

      sampleTime_ = 0L;

      internalGetMutableMetricTags().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.betasoft.dp.metric.merge.protobuf.MetricsValueProto.internal_static_MetricValue_descriptor;
    }

    @java.lang.Override
    public cn.betasoft.dp.metric.merge.protobuf.MetricValue getDefaultInstanceForType() {
      return cn.betasoft.dp.metric.merge.protobuf.MetricValue.getDefaultInstance();
    }

    @java.lang.Override
    public cn.betasoft.dp.metric.merge.protobuf.MetricValue build() {
      cn.betasoft.dp.metric.merge.protobuf.MetricValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.betasoft.dp.metric.merge.protobuf.MetricValue buildPartial() {
      cn.betasoft.dp.metric.merge.protobuf.MetricValue result = new cn.betasoft.dp.metric.merge.protobuf.MetricValue(this);
      int from_bitField0_ = bitField0_;
      result.moType_ = moType_;
      result.metricName_ = metricName_;
      result.moId_ = moId_;
      result.metricValue_ = metricValue_;
      result.sampleTime_ = sampleTime_;
      result.metricTags_ = internalGetMetricTags();
      result.metricTags_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.betasoft.dp.metric.merge.protobuf.MetricValue) {
        return mergeFrom((cn.betasoft.dp.metric.merge.protobuf.MetricValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.betasoft.dp.metric.merge.protobuf.MetricValue other) {
      if (other == cn.betasoft.dp.metric.merge.protobuf.MetricValue.getDefaultInstance()) return this;
      if (!other.getMoType().isEmpty()) {
        moType_ = other.moType_;
        onChanged();
      }
      if (!other.getMetricName().isEmpty()) {
        metricName_ = other.metricName_;
        onChanged();
      }
      if (!other.getMoId().isEmpty()) {
        moId_ = other.moId_;
        onChanged();
      }
      if (other.getMetricValue() != 0D) {
        setMetricValue(other.getMetricValue());
      }
      if (other.getSampleTime() != 0L) {
        setSampleTime(other.getSampleTime());
      }
      internalGetMutableMetricTags().mergeFrom(
          other.internalGetMetricTags());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.betasoft.dp.metric.merge.protobuf.MetricValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.betasoft.dp.metric.merge.protobuf.MetricValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object moType_ = "";
    /**
     * <code>string moType = 1;</code>
     * @return The moType.
     */
    public java.lang.String getMoType() {
      java.lang.Object ref = moType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string moType = 1;</code>
     * @return The bytes for moType.
     */
    public com.google.protobuf.ByteString
        getMoTypeBytes() {
      java.lang.Object ref = moType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string moType = 1;</code>
     * @param value The moType to set.
     * @return This builder for chaining.
     */
    public Builder setMoType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      moType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string moType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoType() {
      
      moType_ = getDefaultInstance().getMoType();
      onChanged();
      return this;
    }
    /**
     * <code>string moType = 1;</code>
     * @param value The bytes for moType to set.
     * @return This builder for chaining.
     */
    public Builder setMoTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      moType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metricName_ = "";
    /**
     * <code>string metricName = 2;</code>
     * @return The metricName.
     */
    public java.lang.String getMetricName() {
      java.lang.Object ref = metricName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metricName = 2;</code>
     * @return The bytes for metricName.
     */
    public com.google.protobuf.ByteString
        getMetricNameBytes() {
      java.lang.Object ref = metricName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metricName = 2;</code>
     * @param value The metricName to set.
     * @return This builder for chaining.
     */
    public Builder setMetricName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metricName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string metricName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricName() {
      
      metricName_ = getDefaultInstance().getMetricName();
      onChanged();
      return this;
    }
    /**
     * <code>string metricName = 2;</code>
     * @param value The bytes for metricName to set.
     * @return This builder for chaining.
     */
    public Builder setMetricNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metricName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object moId_ = "";
    /**
     * <code>string moId = 3;</code>
     * @return The moId.
     */
    public java.lang.String getMoId() {
      java.lang.Object ref = moId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string moId = 3;</code>
     * @return The bytes for moId.
     */
    public com.google.protobuf.ByteString
        getMoIdBytes() {
      java.lang.Object ref = moId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string moId = 3;</code>
     * @param value The moId to set.
     * @return This builder for chaining.
     */
    public Builder setMoId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      moId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string moId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoId() {
      
      moId_ = getDefaultInstance().getMoId();
      onChanged();
      return this;
    }
    /**
     * <code>string moId = 3;</code>
     * @param value The bytes for moId to set.
     * @return This builder for chaining.
     */
    public Builder setMoIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      moId_ = value;
      onChanged();
      return this;
    }

    private double metricValue_ ;
    /**
     * <code>double metricValue = 4;</code>
     * @return The metricValue.
     */
    @java.lang.Override
    public double getMetricValue() {
      return metricValue_;
    }
    /**
     * <code>double metricValue = 4;</code>
     * @param value The metricValue to set.
     * @return This builder for chaining.
     */
    public Builder setMetricValue(double value) {
      
      metricValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double metricValue = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricValue() {
      
      metricValue_ = 0D;
      onChanged();
      return this;
    }

    private long sampleTime_ ;
    /**
     * <code>int64 sampleTime = 5;</code>
     * @return The sampleTime.
     */
    @java.lang.Override
    public long getSampleTime() {
      return sampleTime_;
    }
    /**
     * <code>int64 sampleTime = 5;</code>
     * @param value The sampleTime to set.
     * @return This builder for chaining.
     */
    public Builder setSampleTime(long value) {
      
      sampleTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sampleTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleTime() {
      
      sampleTime_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metricTags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetricTags() {
      if (metricTags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetricTagsDefaultEntryHolder.defaultEntry);
      }
      return metricTags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMetricTags() {
      onChanged();;
      if (metricTags_ == null) {
        metricTags_ = com.google.protobuf.MapField.newMapField(
            MetricTagsDefaultEntryHolder.defaultEntry);
      }
      if (!metricTags_.isMutable()) {
        metricTags_ = metricTags_.copy();
      }
      return metricTags_;
    }

    public int getMetricTagsCount() {
      return internalGetMetricTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */

    @java.lang.Override
    public boolean containsMetricTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetricTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetricTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetricTags() {
      return getMetricTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetricTagsMap() {
      return internalGetMetricTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getMetricTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetricTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getMetricTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetricTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMetricTags() {
      internalGetMutableMetricTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */

    public Builder removeMetricTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMetricTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMetricTags() {
      return internalGetMutableMetricTags().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */
    public Builder putMetricTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMetricTags().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metricTags = 6;</code>
     */

    public Builder putAllMetricTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetricTags().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MetricValue)
  }

  // @@protoc_insertion_point(class_scope:MetricValue)
  private static final cn.betasoft.dp.metric.merge.protobuf.MetricValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.betasoft.dp.metric.merge.protobuf.MetricValue();
  }

  public static cn.betasoft.dp.metric.merge.protobuf.MetricValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetricValue>
      PARSER = new com.google.protobuf.AbstractParser<MetricValue>() {
    @java.lang.Override
    public MetricValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetricValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetricValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetricValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.betasoft.dp.metric.merge.protobuf.MetricValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

