// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricValue.proto

package cn.betasoft.dp.metric.merge.protobuf;

public interface MetricValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetricValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string moType = 1;</code>
   * @return The moType.
   */
  java.lang.String getMoType();
  /**
   * <code>string moType = 1;</code>
   * @return The bytes for moType.
   */
  com.google.protobuf.ByteString
      getMoTypeBytes();

  /**
   * <code>string metricName = 2;</code>
   * @return The metricName.
   */
  java.lang.String getMetricName();
  /**
   * <code>string metricName = 2;</code>
   * @return The bytes for metricName.
   */
  com.google.protobuf.ByteString
      getMetricNameBytes();

  /**
   * <code>string moId = 3;</code>
   * @return The moId.
   */
  java.lang.String getMoId();
  /**
   * <code>string moId = 3;</code>
   * @return The bytes for moId.
   */
  com.google.protobuf.ByteString
      getMoIdBytes();

  /**
   * <code>double metricValue = 4;</code>
   * @return The metricValue.
   */
  double getMetricValue();

  /**
   * <code>int64 sampleTime = 5;</code>
   * @return The sampleTime.
   */
  long getSampleTime();

  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  int getMetricTagsCount();
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  boolean containsMetricTags(
      java.lang.String key);
  /**
   * Use {@link #getMetricTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetricTags();
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetricTagsMap();
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */

  java.lang.String getMetricTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metricTags = 6;</code>
   */

  java.lang.String getMetricTagsOrThrow(
      java.lang.String key);
}
