// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metricValue.proto

package cn.betasoft.dp.metric.merge.protobuf;

public final class MetricsValueProto {
  private MetricsValueProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MetricValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MetricValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MetricValue_MetricTagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MetricValue_MetricTagsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021metricValue.proto\"\315\001\n\013MetricValue\022\016\n\006m" +
      "oType\030\001 \001(\t\022\022\n\nmetricName\030\002 \001(\t\022\014\n\004moId\030" +
      "\003 \001(\t\022\023\n\013metricValue\030\004 \001(\001\022\022\n\nsampleTime" +
      "\030\005 \001(\003\0220\n\nmetricTags\030\006 \003(\0132\034.MetricValue" +
      ".MetricTagsEntry\0321\n\017MetricTagsEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B;\n$cn.betaso" +
      "ft.dp.metric.merge.protobufB\021MetricsValu" +
      "eProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MetricValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MetricValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MetricValue_descriptor,
        new java.lang.String[] { "MoType", "MetricName", "MoId", "MetricValue", "SampleTime", "MetricTags", });
    internal_static_MetricValue_MetricTagsEntry_descriptor =
      internal_static_MetricValue_descriptor.getNestedTypes().get(0);
    internal_static_MetricValue_MetricTagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MetricValue_MetricTagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
